import time
import jwt
import requests
from backend.history_store import safe_record_history
from google.cloud import secretmanager

PROJECT_ID = "project-cf538dc4-c334-46fa-aac"

def get_secret(secret_id):
    client = secretmanager.SecretManagerServiceClient()
    name = f"projects/{PROJECT_ID}/secrets/{secret_id}/versions/latest"
    response = client.access_secret_version(request={"name": name})
    return response.payload.data.decode("UTF-8")

def create_jwt():
    app_id = get_secret("github-app-id")
    private_key = get_secret("github-private-key")

    payload = {
        "iat": int(time.time()) - 60,
        "exp": int(time.time()) + 600,
        "iss": app_id
    }

    return jwt.encode(
        payload,
        private_key,
        algorithm="RS256"
    )

def get_installation_token():
    installation_id = get_secret("github-installation-id")

    url = (
        "https://api.github.com/app/installations/"
        f"{installation_id}/access_tokens"
    )

    last_error = None

    for attempt in range(1, 5):
        try:
            jwt_token = create_jwt()

            headers = {
                "Authorization": f"Bearer {jwt_token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28"
            }

            response = requests.post(url, headers=headers, timeout=20)
            response.raise_for_status()

            return response.json()["token"]

        except Exception as e:
            last_error = e

            if attempt >= 4:
                break

            sleep_seconds = 2 * attempt
            print(
                "GitHub installation token request retry: "
                f"attempt={attempt}/4 sleep_seconds={sleep_seconds} error={e}",
                flush=True,
            )
            time.sleep(sleep_seconds)

    raise last_error

def github_headers(accept="application/vnd.github+json"):
    token = get_installation_token()

    return {
        "Authorization": f"Bearer {token}",
        "Accept": accept,
        "X-GitHub-Api-Version": "2022-11-28"
    }

def get_pr_diff(owner, repo, pr_number):
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"

    response = requests.get(
        url,
        headers=github_headers("application/vnd.github.v3.diff"),
        timeout=10
    )

    response.raise_for_status()
    return response.text

def post_pr_comment(owner, repo, pr_number, body):
    url = (
        f"https://api.github.com/repos/"
        f"{owner}/{repo}/issues/{pr_number}/comments"
    )

    response = requests.post(
        url,
        headers=github_headers(),
        json={"body": body},
        timeout=10
    )

    response.raise_for_status()
    return response.json()

def create_pull_request(owner, repo, head, base, title, body):
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls"

    response = requests.post(
        url,
        headers=github_headers(),
        json={
            "title": title,
            "head": head,
            "base": base,
            "body": body
        },
        timeout=10
    )

    if response.status_code == 422:
        return {
            "status": "already_exists_or_invalid",
            "detail": response.json()
        }

    response.raise_for_status()
    return response.json()

if __name__ == "__main__":
    print("github_pr.py loaded safely. No PR is created automatically.")

# --- Security Review Workflow comment upsert helpers ---

DEVSECOPS_COMMENT_MARKER = "<!-- devsecops-ai-agent-review -->"

def list_issue_comments(owner, repo, issue_number):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"

    res = requests.get(
        url,
        headers=github_headers()
    )
    res.raise_for_status()
    return res.json()


def update_issue_comment(owner, repo, comment_id, body):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/comments/{comment_id}"

    res = requests.patch(
        url,
        headers=github_headers(),
        json={
            "body": body
        }
    )
    res.raise_for_status()
    return res.json()


def post_pr_comment(owner, repo, pr_number, body):
    """
    Create or update a single Security Review Workflow comment on a PR.
    This intentionally overrides the earlier post_pr_comment definition.
    """

    if DEVSECOPS_COMMENT_MARKER not in body:
        body = DEVSECOPS_COMMENT_MARKER + "\n" + body

    comments = list_issue_comments(owner, repo, pr_number)

    for comment in reversed(comments):
        comment_body = comment.get("body") or ""

        if (
            DEVSECOPS_COMMENT_MARKER in comment_body
            or "This comment was generated by Security Review Workflow" in comment_body
            or "Security Review Report" in comment_body
        ):
            result = update_issue_comment(
                owner,
                repo,
                comment["id"],
                body
            )

            safe_record_history("review_comment_updated", {
                "owner": owner,
                "repo": repo,
                "pr_number": pr_number,
                "comment_url": result.get("html_url"),
                "comment_id": result.get("id"),
            })

            return result

    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"

    res = requests.post(
        url,
        headers=github_headers(),
        json={
            "body": body
        }
    )
    res.raise_for_status()
    return res.json()


# --- Security remediation PR helpers ---

def get_pull_request(owner, repo, pr_number):
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"

    res = requests.get(
        url,
        headers=github_headers(),
        timeout=10,
    )
    res.raise_for_status()
    return res.json()


def list_pr_files(owner, repo, pr_number):
    files = []
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}/files"

    while url:
        res = requests.get(
            url,
            headers=github_headers(),
            params={"per_page": 100} if "per_page" not in url else None,
            timeout=10,
        )
        res.raise_for_status()
        files.extend(res.json())
        url = res.links.get("next", {}).get("url")

    return files


def create_branch(owner, repo, branch_name, sha):
    url = f"https://api.github.com/repos/{owner}/{repo}/git/refs"

    res = requests.post(
        url,
        headers=github_headers(),
        json={
            "ref": f"refs/heads/{branch_name}",
            "sha": sha,
        },
        timeout=10,
    )
    res.raise_for_status()
    return res.json()


def get_file_text(owner, repo, path, ref):
    import base64
    from urllib.parse import quote

    encoded_path = quote(path, safe="/")
    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{encoded_path}"

    res = requests.get(
        url,
        headers=github_headers(),
        params={"ref": ref},
        timeout=10,
    )
    res.raise_for_status()

    data = res.json()
    content = base64.b64decode(data["content"]).decode("utf-8")

    return {
        "sha": data["sha"],
        "content": content,
    }


def update_file_text(owner, repo, path, branch, content, sha, message):
    import base64
    from urllib.parse import quote

    encoded_path = quote(path, safe="/")
    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{encoded_path}"

    encoded_content = base64.b64encode(content.encode("utf-8")).decode("utf-8")

    res = requests.put(
        url,
        headers=github_headers(),
        json={
            "message": message,
            "content": encoded_content,
            "sha": sha,
            "branch": branch,
        },
        timeout=10,
    )
    res.raise_for_status()
    result = res.json()

    safe_record_history("review_comment_created", {
        "owner": owner,
        "repo": repo,
        "pr_number": pr_number,
        "comment_url": result.get("html_url"),
        "comment_id": result.get("id"),
    })

    return result


def apply_k8s_remediation(content):
    import re

    updated = content
    changes = []

    updated, count = re.subn(
        r'^(\s*)privileged:\s*true\s*(#.*)?$',
        lambda m: f"{m.group(1)}privileged: false" + (f" {m.group(2)}" if m.group(2) else ""),
        updated,
        flags=re.MULTILINE,
    )
    if count:
        changes.append("Set privileged: false")

    updated, count = re.subn(
        r'^(\s*image:\s*["\']?\S+):latest(["\']?\s*(?:#.*)?)$',
        r'\1:stable\2',
        updated,
        flags=re.MULTILINE,
    )
    if count:
        changes.append("Replace latest image tag with stable tag")

    def replace_empty_resources(match):
        indent = match.group(1)
        return (
            f"{indent}resources:\n"
            f"{indent}  requests:\n"
            f"{indent}    cpu: \"100m\"\n"
            f"{indent}    memory: \"128Mi\"\n"
            f"{indent}  limits:\n"
            f"{indent}    cpu: \"500m\"\n"
            f"{indent}    memory: \"512Mi\""
        )

    updated, count = re.subn(
        r'^(\s*)resources:\s*\{\}\s*$',
        replace_empty_resources,
        updated,
        flags=re.MULTILINE,
    )
    if count:
        changes.append("Add CPU and memory requests/limits")

    return updated, changes


def is_k8s_manifest_path(path):
    return path.endswith((".yaml", ".yml"))



def find_existing_remediation_pr(owner, repo, pr_number):
    """
    Find an existing remediation PR for the source PR.
    This prevents creating duplicate remediation PRs for the same source PR.
    """

    matches = []
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
    params = {
        "state": "all",
        "per_page": 100,
    }

    while url:
        res = requests.get(
            url,
            headers=github_headers(),
            params=params,
            timeout=10,
        )
        res.raise_for_status()

        for pr in res.json():
            title = pr.get("title") or ""
            body = pr.get("body") or ""
            head_ref = (pr.get("head") or {}).get("ref") or ""

            if (
                title == f"fix: remediate security findings from PR #{pr_number}"
                or f"Source PR: #{pr_number}" in body
                or head_ref.startswith(f"security-remediation/pr-{pr_number}-")
            ):
                matches.append(pr)

        url = res.links.get("next", {}).get("url")
        params = None

    if not matches:
        return None

    def sort_key(pr):
        state = pr.get("state")
        merged_at = pr.get("merged_at")
        number = pr.get("number") or 0

        if state == "open":
            status_rank = 0
        elif merged_at:
            status_rank = 1
        else:
            status_rank = 2

        return (status_rank, -number)

    return sorted(matches, key=sort_key)[0]

def create_k8s_remediation_pr(owner, repo, pr_number):
    import time

    existing_pr = find_existing_remediation_pr(owner, repo, pr_number)

    if existing_pr:
        return {
            "status": "existing",
            "branch": (existing_pr.get("head") or {}).get("ref"),
            "changed_files": [],
            "applied_changes": [],
            "pull_request": existing_pr,
        }

    pr = get_pull_request(owner, repo, pr_number)
    files = list_pr_files(owner, repo, pr_number)

    base_ref = pr["base"]["ref"]
    source_sha = pr["head"]["sha"]

    branch_name = f"security-remediation/pr-{pr_number}-{int(time.time())}"

    create_branch(owner, repo, branch_name, source_sha)

    changed_files = []
    applied_changes = []

    for item in files:
        path = item.get("filename", "")
        status = item.get("status", "")

        if status == "removed":
            continue

        if not is_k8s_manifest_path(path):
            continue

        current = get_file_text(owner, repo, path, branch_name)
        new_content, changes = apply_k8s_remediation(current["content"])

        if not changes or new_content == current["content"]:
            continue

        update_file_text(
            owner,
            repo,
            path,
            branch_name,
            new_content,
            current["sha"],
            f"fix: remediate Kubernetes security settings in {path}",
        )

        changed_files.append(path)
        applied_changes.extend(changes)

    if not changed_files:
        return {
            "status": "no_changes",
            "branch": branch_name,
            "changed_files": [],
            "applied_changes": [],
        }

    title = f"fix: remediate security findings from PR #{pr_number}"
    body = (
        "This pull request applies approved remediation for Kubernetes security findings.\n\n"
        f"Source PR: #{pr_number}\n\n"
        "Changes applied:\n"
        + "\n".join(f"- {change}" for change in sorted(set(applied_changes)))
        + "\n\nFiles changed:\n"
        + "\n".join(f"- `{path}`" for path in changed_files)
    )

    new_pr = create_pull_request(
        owner,
        repo,
        branch_name,
        base_ref,
        title,
        body,
    )

    return {
        "status": "created",
        "branch": branch_name,
        "changed_files": changed_files,
        "applied_changes": sorted(set(applied_changes)),
        "pull_request": new_pr,
    }
