import time
import jwt
import requests
from google.cloud import secretmanager

PROJECT_ID = "project-cf538dc4-c334-46fa-aac"

def get_secret(secret_id):
    client = secretmanager.SecretManagerServiceClient()
    name = f"projects/{PROJECT_ID}/secrets/{secret_id}/versions/latest"
    response = client.access_secret_version(request={"name": name})
    return response.payload.data.decode("UTF-8")

def create_jwt():
    app_id = get_secret("github-app-id")
    private_key = get_secret("github-private-key")

    payload = {
        "iat": int(time.time()) - 60,
        "exp": int(time.time()) + 600,
        "iss": app_id
    }

    return jwt.encode(
        payload,
        private_key,
        algorithm="RS256"
    )

def get_installation_token():
    installation_id = get_secret("github-installation-id")
    jwt_token = create_jwt()

    url = (
        "https://api.github.com/app/installations/"
        f"{installation_id}/access_tokens"
    )

    headers = {
        "Authorization": f"Bearer {jwt_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    response = requests.post(url, headers=headers, timeout=10)
    response.raise_for_status()

    return response.json()["token"]

def github_headers(accept="application/vnd.github+json"):
    token = get_installation_token()

    return {
        "Authorization": f"Bearer {token}",
        "Accept": accept,
        "X-GitHub-Api-Version": "2022-11-28"
    }

def get_pr_diff(owner, repo, pr_number):
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"

    response = requests.get(
        url,
        headers=github_headers("application/vnd.github.v3.diff"),
        timeout=10
    )

    response.raise_for_status()
    return response.text

def post_pr_comment(owner, repo, pr_number, body):
    url = (
        f"https://api.github.com/repos/"
        f"{owner}/{repo}/issues/{pr_number}/comments"
    )

    response = requests.post(
        url,
        headers=github_headers(),
        json={"body": body},
        timeout=10
    )

    response.raise_for_status()
    return response.json()

def create_pull_request(owner, repo, head, base, title, body):
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls"

    response = requests.post(
        url,
        headers=github_headers(),
        json={
            "title": title,
            "head": head,
            "base": base,
            "body": body
        },
        timeout=10
    )

    if response.status_code == 422:
        return {
            "status": "already_exists_or_invalid",
            "detail": response.json()
        }

    response.raise_for_status()
    return response.json()

if __name__ == "__main__":
    print("github_pr.py loaded safely. No PR is created automatically.")

# --- Security Review Workflow comment upsert helpers ---

DEVSECOPS_COMMENT_MARKER = "<!-- devsecops-ai-agent-review -->"

def list_issue_comments(owner, repo, issue_number):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"

    res = requests.get(
        url,
        headers=github_headers()
    )
    res.raise_for_status()
    return res.json()


def update_issue_comment(owner, repo, comment_id, body):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/comments/{comment_id}"

    res = requests.patch(
        url,
        headers=github_headers(),
        json={
            "body": body
        }
    )
    res.raise_for_status()
    return res.json()


def post_pr_comment(owner, repo, pr_number, body):
    """
    Create or update a single Security Review Workflow comment on a PR.
    This intentionally overrides the earlier post_pr_comment definition.
    """

    if DEVSECOPS_COMMENT_MARKER not in body:
        body = DEVSECOPS_COMMENT_MARKER + "\n" + body

    comments = list_issue_comments(owner, repo, pr_number)

    for comment in reversed(comments):
        comment_body = comment.get("body") or ""

        if (
            DEVSECOPS_COMMENT_MARKER in comment_body
            or "This comment was generated by Security Review Workflow" in comment_body
            or "Security Review Report" in comment_body
        ):
            return update_issue_comment(
                owner,
                repo,
                comment["id"],
                body
            )

    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"

    res = requests.post(
        url,
        headers=github_headers(),
        json={
            "body": body
        }
    )
    res.raise_for_status()
    return res.json()
