apiVersion: apps/v1
kind: Deployment
metadata:
  name: approve-remediation-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approve-remediation-demo
  template:
    metadata:
      labels:
        app: approve-remediation-demo
    spec:
      containers:
        - name: app
          image: nginx:stable
          securityContext:
            privileged: false
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            readOnlyRootFilesystem: false
