apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
spec:
  template:
    spec:
      containers:
        - name: app
          image: nginx:latest
          securityContext:
            privileged: true
          resources: {}

# webhook live test 2026-06-29T12:20:42+00:00

# webhook synchronize test 2026-06-29T12:21:58+00:00

# upsert webhook test 2026-06-29T12:32:20+00:00

# signed webhook test 2026-06-29T12:44:02+00:00

# real signed webhook test 2026-06-29T13:03:39+00:00

# final signed webhook test 2026-06-29T13:04:26+00:00
